# Install script for directory: /home/parallels/clion/src

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "/usr/local")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "Debug")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

# Install shared libraries without execute permission?
if(NOT DEFINED CMAKE_INSTALL_SO_NO_EXE)
  set(CMAKE_INSTALL_SO_NO_EXE "1")
endif()

# Is this installation the result of a crosscompile?
if(NOT DEFINED CMAKE_CROSSCOMPILING)
  set(CMAKE_CROSSCOMPILING "FALSE")
endif()

# Set default install directory permissions.
if(NOT DEFINED CMAKE_OBJDUMP)
  set(CMAKE_OBJDUMP "/usr/bin/objdump")
endif()

if(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  include("/home/parallels/clion/build-linux/src/DataStructure/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/Test/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/EnumClass/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/weakPtr/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/reference/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/orm/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/dynamic_cast/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/Execute_before_main/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/rpc/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/asctime/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/addressof/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/Copy_structure/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/memory_model/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/asio/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/auto/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/inline/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/any/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/backtrace/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/dlopen/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/DNS/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/enableShard/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/fstream/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/stub/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/proxy/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/memory/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/new/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/regex/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/register/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/rpcexp/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/sharedPtr/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/sqlite3/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/syslog/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/ThreadPool/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/TimerTest/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/tuple/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/reference_wrapper/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/unordered_set/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/type/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/typeid/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/getline/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/json/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/Variable_parameter_template/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/sizeof.../cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/folded_expression/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/folded_expression2/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/fold_expression_empty_packet_processing/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/class_template/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/visit_struct/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/optional/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/sscanf/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/popen/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/protobuf/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/gcovr/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/async/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/inlineStatic/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/gtest/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/dbg/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/boostLambda/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/giomm/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/sqlit3pp/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/invocable/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/promise/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/packaged_task/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/libevent/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/looper/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/rpc_client/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/vec/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/stream/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/threadTest/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/runableHandlerTest/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/string/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/overload/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/quoted/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/as_bytes/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/atomic/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/boolalpha/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/match_format/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/locale/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/strategy/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/Observer/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/enable_shared_from_this/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/from_chars/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/mem_fn/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/chrnon/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/char/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/subprocess1/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/Throw_an_exception_at_destructor_time/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/virtual/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/log4cpp/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/imgui/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/Disjoint-setDataStructure/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/stringAssign/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/strto/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/udl/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/unique_ptr/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/conditional/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/netd/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/ptr/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/uuid/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/netd1/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/pythonC++/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/ifc/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/engineTest/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/utils/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/DateBaseTest/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/align/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/tcpServer/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/tcpClient/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/jsoncpp/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/msgpackTest/cmake_install.cmake")

endif()

