# Install script for directory: /home/parallels/clion/src/DataStructure

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "/usr/local")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "Debug")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

# Install shared libraries without execute permission?
if(NOT DEFINED CMAKE_INSTALL_SO_NO_EXE)
  set(CMAKE_INSTALL_SO_NO_EXE "1")
endif()

# Is this installation the result of a crosscompile?
if(NOT DEFINED CMAKE_CROSSCOMPILING)
  set(CMAKE_CROSSCOMPILING "FALSE")
endif()

# Set default install directory permissions.
if(NOT DEFINED CMAKE_OBJDUMP)
  set(CMAKE_OBJDUMP "/usr/bin/objdump")
endif()

if(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  include("/home/parallels/clion/build-linux/src/DataStructure/22/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/DataStructure/56/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/DataStructure/105/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/DataStructure/129/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/DataStructure/141/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/DataStructure/148/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/DataStructure/211/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/DataStructure/718/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/DataStructure/1277/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/DataStructure/26Z/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/DataStructure/6Z/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/DataStructure/38Z/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/DataStructure/33Z/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/DataStructure/1/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/DataStructure/5/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/DataStructure/15/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/DataStructure/20/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/DataStructure/31/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/DataStructure/33/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/DataStructure/53/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/DataStructure/54/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/DataStructure/60/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/DataStructure/102/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/DataStructure/102_2/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/DataStructure/102_3/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/DataStructure/103/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/DataStructure/103_2/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/DataStructure/121/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/DataStructure/199/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/DataStructure/200/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/DataStructure/202_2/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/DataStructure/236/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/DataStructure/300/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/DataStructure/1003/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/DataStructure/997/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/DataStructure/1791/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/DataStructure/1971/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/DataStructure/455/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/DataStructure/135/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/DataStructure/605/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/DataStructure/452/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/DataStructure/763/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/DataStructure/122/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/DataStructure/167/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/DataStructure/88/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/DataStructure/142/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/DataStructure/76/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/DataStructure/633/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/DataStructure/680/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/DataStructure/524/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/DataStructure/69/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/DataStructure/34/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/DataStructure/81/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/DataStructure/154/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/DataStructure/540/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/DataStructure/quickSort/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/DataStructure/215/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/DataStructure/347/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/DataStructure/451/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/DataStructure/695/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/DataStructure/547/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/DataStructure/417/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/DataStructure/46/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/DataStructure/77/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/DataStructure/79/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/DataStructure/934/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/DataStructure/130/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/DataStructure/257/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/DataStructure/47/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/DataStructure/40/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/DataStructure/310/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/DataStructure/311/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/DataStructure/FindStonePair/cmake_install.cmake")
  include("/home/parallels/clion/build-linux/src/DataStructure/RabbitGoesHome/cmake_install.cmake")

endif()

