# Install script for directory: /media/psf/Home/Desktop/git/C-/mac/myproject/src

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "/usr/local")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

# Install shared libraries without execute permission?
if(NOT DEFINED CMAKE_INSTALL_SO_NO_EXE)
  set(CMAKE_INSTALL_SO_NO_EXE "1")
endif()

# Is this installation the result of a crosscompile?
if(NOT DEFINED CMAKE_CROSSCOMPILING)
  set(CMAKE_CROSSCOMPILING "FALSE")
endif()

# Set default install directory permissions.
if(NOT DEFINED CMAKE_OBJDUMP)
  set(CMAKE_OBJDUMP "/usr/bin/objdump")
endif()

if(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/Test/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/EnumClass/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/weakPtr/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/reference/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/orm/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/dynamic_cast/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/Execute_before_main/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/rpc/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/asctime/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/addressof/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/22/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/56/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/69/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/105/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/129/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/141/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/148/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/211/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/417/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/718/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/1277/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/26Z/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/6Z/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/38Z/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/33Z/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/1/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/5/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/15/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/20/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/31/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/33/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/46/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/53/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/54/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/60/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/102/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/102_2/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/102_3/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/103/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/103_2/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/121/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/199/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/200/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/202_2/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/215/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/236/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/300/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/1003/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/Copy_structure/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/memory_model/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/asio/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/auto/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/inline/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/any/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/backtrace/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/dlopen/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/DNS/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/enableShard/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/fstream/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/memory/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/new/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/regex/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/register/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/rpcexp/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/sharedPtr/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/sqlite3/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/syslog/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/ThreadPool/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/TimerTest/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/tuple/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/reference_wrapper/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/unordered_set/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/type/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/typeid/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/getline/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/json/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/Variable_parameter_template/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/sizeof.../cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/folded_expression/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/folded_expression2/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/fold_expression_empty_packet_processing/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/class_template/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/visit_struct/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/optional/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/sscanf/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/popen/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/gcovr/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/async/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/inlineStatic/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/gtest/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/dbg/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/boostLambda/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/giomm/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/sqlit3pp/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/invocable/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/promise/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/packaged_task/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/libevent/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/looper/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/rpc_client/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/vec/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/stream/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/threadTest/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/runableHandlerTest/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/string/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/overload/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/quoted/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/as_bytes/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/atomic/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/boolalpha/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/match_format/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/locale/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/strategy/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/Observer/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/enable_shared_from_this/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/from_chars/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/mem_fn/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/chrnon/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/char/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/subprocess1/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/Throw_an_exception_at_destructor_time/cmake_install.cmake")
  include("/media/psf/Home/Desktop/git/C-/mac/myproject/build1/src/virtual/cmake_install.cmake")

endif()

